In [ ]:
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.animation import  FuncAnimation

# Build in Methods


In [ ]:
np.zeros((5, 5))

### Arange
Return evenly spaced wihtin given interval

In [ ]:
np.arange(0, 100)

In [ ]:
np.arange(0, 11, 2)

#### Linspace
Return evenly speaced numbers over a specified Interval
Mengembalikan angka dengan jarak yang sama selama interval tertentu.

In [ ]:
np.linspace(5, 10, 3)

In [ ]:
np.linspace(0, 10, 50)

#### Eye
Creates an identity Matrix

In [ ]:
np.eye(3)

In [ ]:
np.eye(5)

#### Random
Numpy also has lots of ways to create random number arrays

#### rand
Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1)

In [ ]:
np.random.rand(3)*2

In [ ]:
np.random.rand(5, 5)

#### randn
Return a sample (or samples ) fro the "Standard normal" distribution. Unlike rand which is uniform

Kembalikan sampel (atau sampel) dari distribusi "Standar normal". Berbeda dengan rand yang seragam

In [ ]:
np.random.randn(3)

In [ ]:
np.random.randn(5,5)

#### Array Attributes and Methods


In [29]:
arr = np.arange(25)
ranarr = np.random.randint(0, 50, 10)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
ranarr

array([40,  5,  1, 12, 36, 30, 10, 49, 13, 26])

#### Reshape

In [32]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### Max, Min, ArgMax, ArgMin
These are useful methods for finding max or min values. Or to find their index locations using ArgMin or ArgMax

In [33]:
ranarr.max()

49

In [34]:
ranarr.argmax()
# return index yang memiliki value maximal

7

In [35]:
ranarr.min()

1

#### dType
Untuk mengetahui suatu tipe data

In [37]:
arr.dtype

dtype('int32')