In [30]:
import numpy as np

# NumPy Indexing and Selection

Disini akan dijelaskan cara mendapatkan index dalam Numpy

In [31]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python list


In [32]:
arr[5]

5

In [33]:
arr[1:5]

array([1, 2, 3, 4])

#### Broadcasting
Numpy arrays differ from a normal python list because their ability to broadcast

In [34]:
arr[0 : 5] = 100

In [35]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [36]:
# Reset array
arr = np.arange(0, 11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
#important notes on slices
slice_of_arr = arr[0:6]

slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [38]:
slice_of_arr[:] = 100

slice_of_arr

array([100, 100, 100, 100, 100, 100])

In [39]:
ar_copy = arr.copy()

ar_copy

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

#### Indexing a 2D Array (Matrices)
Sama kek c++

In [40]:
arr_2d = np.array(([5, 10, 15], [20, 25, 30], [35, 40, 45]))

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [41]:
arr_2d[1]

array([20, 25, 30])

In [42]:
arr_2d[1][1]

25

In [43]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

#### Fancy Indexing
Fanci indexing allows you to select entire rows or columns out of order, to show this, let's quickly build out a numpy Array

In [44]:
arr2d = np.zeros((10, 10))
arr_length = arr2d.shape[1]

In [45]:
for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

#### Selection
Let's briefly go over how to use brackets for selection based off of  comparison operators

In [46]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [48]:
bool_arr = arr > 4

In [49]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [50]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])